### ISSUE TITLE
Album upload don't work

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#3] opened 2019-02-21 08:29 UTC
Hi Rune,
this is a great project! Please continue.
I'm trying the version for Windows 10.
The retrieval of the existing albums works well.
Now I want to upload the folder "c: \Users\Andreas\Pictures\1705050_Couch\" as an album. That fails with "Upload summary:
c: \ Users \ Andreas \ Pictures \ 1705050_Couch \: An exception occured during Album upload ".
What can I do?
Greetings from Germany / Berlin

**Comment by runerasmussen** [comment] 2019-02-21 09:37
Hi @praetor100 

Please check the log file log/google-photos-upload.log
This file should have details on the Exception. Please share the Exception message or entire log file here so I can better comment on it (it may be a simple issue with Google's Cloud API at the time you tried, I have seen that and a retry worked well)

**Comment by praetor100** [comment] 2019-02-21 09:50
I just tried it again. Unfortunately without success.
Here are the logs:

**google-photos-upload-internal.log**
2019-02-21 10:39:17.1780 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:39:17.1780 Info Loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:39:17.1956 Info NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.4.0.867. Product version: 1.4.0.
2019-02-21 10:39:17.1956 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll succeeded!
2019-02-21 10:39:17.2073 Info Message Template Auto Format enabled
2019-02-21 10:39:17.2735 Info Adding target File Target[target1]
2019-02-21 10:39:17.2735 Info Adding target Console Target[target2]
2019-02-21 10:39:17.3006 Info Configured from an XML element in C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\nlog.config...
2019-02-21 10:39:17.3255 Info Found 21 configuration items
2019-02-21 10:39:18.8725 Info Logger closing down...
2019-02-21 10:39:18.8956 Info Closing old configuration.
2019-02-21 10:39:18.9521 Info Logger has been closed down.
2019-02-21 10:39:18.9623 Info Shutting down logging...
2019-02-21 10:39:18.9733 Info Logger has been shut down.
2019-02-21 10:39:20.7816 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:39:20.7900 Info Loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:39:20.7900 Info NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.4.0.867. Product version: 1.4.0.
2019-02-21 10:39:20.8034 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll succeeded!
2019-02-21 10:39:20.8034 Info Message Template Auto Format enabled
2019-02-21 10:39:20.8714 Info Adding target File Target[target1]
2019-02-21 10:39:20.8778 Info Adding target Console Target[target2]
2019-02-21 10:39:20.8778 Info Configured from an XML element in C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\nlog.config...
2019-02-21 10:39:20.9138 Info Found 21 configuration items
2019-02-21 10:41:45.4735 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:41:45.4735 Info Loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 10:41:45.4917 Info NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.4.0.867. Product version: 1.4.0.
2019-02-21 10:41:45.4917 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll succeeded!
2019-02-21 10:41:45.5029 Info Message Template Auto Format enabled
2019-02-21 10:41:45.5649 Info Adding target File Target[target1]
2019-02-21 10:41:45.5649 Info Adding target Console Target[target2]
2019-02-21 10:41:45.5848 Info Configured from an XML element in C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\nlog.config...
2019-02-21 10:41:45.6079 Info Found 21 configuration items
2019-02-21 10:42:15.0410 Info Logger closing down...
2019-02-21 10:42:15.0617 Info Closing old configuration.
2019-02-21 10:42:15.1358 Info Logger has been closed down.
2019-02-21 10:42:15.1462 Info Shutting down logging...
2019-02-21 10:42:15.1462 Info Logger has been shut down.

**google-photos-upload.log**
2019/02/21 10:39:44.637|ERROR|An exception occured Object reference not set to an instance of an object.
2019/02/21 10:42:10.120|ERROR|An exception occured Object reference not set to an instance of an object.

As a test, I also deactivated the two-step login in Google. Unfortunately that did not help.

**Comment by runerasmussen** [comment] 2019-02-21 09:57
Thanks for sharing the log file. It unfortunately does not reveal much, but I will try to replicate on a Windows 10 machine (have mostly used Mac) over the weekend.
Please can you describe what you do to see this error? I assume a browser window open up. Describe it all please incl. what browser it opens up for the authentication.

**Comment by praetor100** [comment] 2019-02-21 10:24
I reset everything again. The video shows the first call of the program, the approval of your tool in Google, the successful retrieval of existing albums from Google Photo. The creation of a new album then fails again.
https://www.dropbox.com/s/9fr9zqa1nj03f2t/Video_2019-02-21_111640.wmv?dl=0

**Comment by snakefoot** [comment] 2019-02-21 17:06
Consider to modify the nlog.config so this line:

`layout="${date}|${level:uppercase=true}|${message} ${exception}" />`

Becomes:

`layout="${date}|${level:uppercase=true}|${message} ${exception:format=tostring}" />`

Consider to also update the official Nlog.config:

https://github.com/runerasmussen/google-photos-upload/blob/3bb18bbec12a905d0a98988d874ef8ce14fe3e23/google-photos-upload/google-photos-upload/nlog.config#L14

**Comment by runerasmussen** [comment] 2019-02-21 20:23
@snakefoot, thanks for catching that logging config issue. 

@praetor100 on your local pc please update the file NLog.config as suggested and rerun the tool, then you should see a more detailed exception message in the log, which you can post here.

**Comment by runerasmussen** [comment] 2019-02-21 20:24
I will fix the logging config issue in the next Pull Request soon

**Comment by praetor100** [comment] 2019-02-21 20:42
Here are the logs based on the modified NLog.config file:

**google-photos-upload-internal.log**
2019-02-21 21:36:18.0785 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 21:36:18.0934 Info Loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 21:36:18.0934 Info NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.4.0.867. Product version: 1.4.0.
2019-02-21 21:36:18.1083 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll succeeded!
2019-02-21 21:36:18.1083 Info Message Template Auto Format enabled
2019-02-21 21:36:18.1947 Info Adding target File Target[target1]
2019-02-21 21:36:18.1947 Info Adding target Console Target[target2]
2019-02-21 21:36:18.2138 Info Configured from an XML element in C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\nlog.config...
2019-02-21 21:36:18.2385 Info Found 21 configuration items
2019-02-21 21:36:48.6044 Info Logger closing down...
2019-02-21 21:36:48.6228 Info Closing old configuration.
2019-02-21 21:36:48.6694 Info Logger has been closed down.
2019-02-21 21:36:48.6801 Info Shutting down logging...
2019-02-21 21:36:48.6887 Info Logger has been shut down.

**google-photos-upload.log**
2019/02/21 21:36:44.992|ERROR|An exception occured System.NullReferenceException: Object reference not set to an instance of an object.
   at google_photos_upload.Model.MyAlbum.SetAlbum() in C:\Users\rune.rasmussen\source\repos\google-photos-upload\google-photos-upload\google-photos-upload\Model\MyAlbum.cs:line 289
   at google_photos_upload.UploadHandler.ProcessAlbumDirectory(String path) in C:\Users\rune.rasmussen\source\repos\google-photos-upload\google-photos-upload\google-photos-upload\UploadHandler.cs:line 133

Could it be that this reference is the problem ?: "C:\Users\rune.rasmussen\source\repos\..."

**Comment by runerasmussen** [comment] 2019-02-21 20:56
@praetor100 now it all makes sense :-)

The issue is that the program is not handling if an existing Album has an empty title. You have such an Album without a title (see 46 seconds into your nice screen capture video).

I will fix this today.

**Comment by runerasmussen** [comment] 2019-02-21 21:26
@praetor100 There is now a new Alpha Release 5 for you to test:
https://github.com/runerasmussen/google-photos-upload/releases/tag/v0.5-alpha

I was unable to duplicate the issue manually in Google Photos to have an Album without a title, so I need your assistance to confirm it is working and until then am holding off on merging into the Master Branch.

**Comment by praetor100** [comment] 2019-02-21 21:30
I'm afraid that's not the solution yet. With a brand new, unique album, the mistake occurs exactly the same way.
I'm testing the new release now.

**Comment by praetor100** [comment] 2019-02-21 21:40
Great! It works basically. :-)
However, there is a problem with one of the pictures. This has (by design) no EXIF block. Your tool could be a bit more tolerant.

**google-photos-upload.log**
2019/02/21 22:32:30.637|INFO|Uploading IMG_20170401_112906.jpg 
2019/02/21 22:32:44.895|INFO|Uploading IMG_20170401_112906_ff.jpg 
2019/02/21 22:32:44.979|ERROR|Failed reading EXIF data... System.NullReferenceException: Object reference not set to an instance of an object.
   at google_photos_upload.Model.MyImage.get_DateImageWasTaken() in C:\Users\rune.rasmussen\Source\Repos\google-photos-upload\google-photos-upload\google-photos-upload\Model\MyImage.cs:line 111
2019/02/21 22:32:45.026|WARN|NOT uploading 'IMG_20170401_112906_ff.jpg' due to file type not supported or EXIF data issue 
2019/02/21 22:32:45.032|INFO|Uploading IMG_20170401_112915.jpg 
2019/02/21 22:32:57.349|INFO|Uploading IMG_20170401_113030.jpg 
2019/02/21 22:33:10.503|ERROR|Album 'dumdidamdam' image file(s) upload failed fully/partly 
2019/02/21 22:33:10.521|INFO|Creating new Album in Google Photos: dumdidamdam 
2019/02/21 22:33:11.352|INFO|Album created: dumdidamdam 
2019/02/21 22:33:11.371|INFO|Adding 4 images to Album 'dumdidamdam' 
2019/02/21 22:33:15.084|ERROR|Images not added fully to Album. Expected 4, only 3 added. 

**google-photos-upload-internal.log**
2019-02-21 22:31:15.2995 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 22:31:15.3118 Info Loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll
2019-02-21 22:31:15.3118 Info NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.4.0.867. Product version: 1.4.0.
2019-02-21 22:31:15.3310 Info Auto loading assembly file: C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\NLog.Extensions.Logging.dll succeeded!
2019-02-21 22:31:15.3310 Info Message Template Auto Format enabled
2019-02-21 22:31:15.4246 Info Adding target File Target[target1]
2019-02-21 22:31:15.4246 Info Adding target Console Target[target2]
2019-02-21 22:31:15.4488 Info Configured from an XML element in C:\Users\Andreas\Downloads\google-photos-upload\win10-x64\nlog.config...
2019-02-21 22:31:15.4797 Info Found 21 configuration items

**Comment by runerasmussen** [comment] 2019-02-22 09:29
Hi @praetor100, great to hear that it works now to upload the pictures.

As for images without EXIF data I decided to excluded these as Google would upload them using Today's date as the date the image was taken:
https://github.com/runerasmussen/google-photos-upload/blob/71695a444f3c63c13abe0ed70514b388e07918b6/google-photos-upload/google-photos-upload/Model/MyImage.cs#L138

I was looking into a more ideal way to handle this, but ran into limitations in the frameworks I tried for manipulating EXIF data (e.g. to set the EXIF date based on the file creation data).
For now there is no plan to change the functionality. If you see such a need please raise a separate Issue for it which I will treat it as an Enhancement request.

I'm closing this Issue given it has been resolved.

**Closed by runerasmussen** 2019-02-22 09:29 UTC
Labels: bug
